"""empty message

Revision ID: 8d72b807fed1
Revises: 
Create Date: 2023-04-03 08:17:11.343547

"""
from alembic import op
import SQLAlchemy as sa


# revision identifiers, used by Alembic.
revision = '8d72b807fed1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['t_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=32), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['t_menu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('t_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('t_attribute',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('val', sa.String(length=255), nullable=True),
    sa.Column('_type', sa.Enum('static', 'dynamic'), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['t_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('introduce', sa.Text(), nullable=True),
    sa.Column('big_img', sa.String(length=255), nullable=True),
    sa.Column('small_img', sa.String(length=255), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('is_promote', sa.Integer(), nullable=True),
    sa.Column('hot_number', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('cid_one', sa.Integer(), nullable=True),
    sa.Column('cid_two', sa.Integer(), nullable=True),
    sa.Column('cid_three', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid_one'], ['t_category.id'], ),
    sa.ForeignKeyConstraint(['cid_three'], ['t_category.id'], ),
    sa.ForeignKeyConstraint(['cid_two'], ['t_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_roles_menus',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('menus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menus_id'], ['t_menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['t_roles.id'], )
    )
    op.create_table('t_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('pwd', sa.String(length=128), nullable=True),
    sa.Column('nick_name', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['t_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('t_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('pay_status', sa.Integer(), nullable=True),
    sa.Column('is_send', sa.Integer(), nullable=True),
    sa.Column('fapiao_title', sa.String(length=255), nullable=True),
    sa.Column('fapiao_content', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['t_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_picture',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['t_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_product_attr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('val', sa.String(length=256), nullable=True),
    sa.Column('_type', sa.Enum('static', 'dynamic'), nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['t_attribute.id'], ),
    sa.ForeignKeyConstraint(['pid'], ['t_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_express',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oid', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('update_time', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['oid'], ['t_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_order_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oid', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['oid'], ['t_order.id'], ),
    sa.ForeignKeyConstraint(['pid'], ['t_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_order_detail')
    op.drop_table('t_express')
    op.drop_table('t_product_attr')
    op.drop_table('t_picture')
    op.drop_table('t_order')
    op.drop_table('t_users')
    op.drop_table('t_roles_menus')
    op.drop_table('t_product')
    op.drop_table('t_attribute')
    op.drop_table('t_roles')
    op.drop_table('t_menu')
    op.drop_table('t_category')
    # ### end Alembic commands ###
